# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fitness.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfitness.proto\"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"<\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x13\n\x04quat\x18\x04 \x01(\x0b\x32\x05.Quat\"\'\n\x04\x43ube\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x04pose\x18\x02 \x01(\x0b\x32\x05.Pose\")\n\x03Tap\x12\x0f\n\x07\x63ube_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"B\n\x08Sequence\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x05\x63ubes\x18\x02 \x03(\x0b\x32\x05.Cube\x12\x12\n\x04taps\x18\x03 \x03(\x0b\x32\x04.Tap\"C\n\x12\x41\x64\x64SequenceRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x1b\n\x08sequence\x18\x03 \x01(\x0b\x32\t.Sequence\"#\n\x10\x41\x64\x64SequenceReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x16GetSequenceListRequest\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x04\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"4\n\x14GetSequenceListReply\x12\x1c\n\tsequences\x18\x01 \x03(\x0b\x32\t.SequenceB\x18\xaa\x02\x15GrpcFitnessGameClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fitness_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\025GrpcFitnessGameClient'
  _globals['_QUAT']._serialized_start=17
  _globals['_QUAT']._serialized_end=67
  _globals['_POSE']._serialized_start=69
  _globals['_POSE']._serialized_end=129
  _globals['_CUBE']._serialized_start=131
  _globals['_CUBE']._serialized_end=170
  _globals['_TAP']._serialized_start=172
  _globals['_TAP']._serialized_end=213
  _globals['_SEQUENCE']._serialized_start=215
  _globals['_SEQUENCE']._serialized_end=281
  _globals['_ADDSEQUENCEREQUEST']._serialized_start=283
  _globals['_ADDSEQUENCEREQUEST']._serialized_end=350
  _globals['_ADDSEQUENCEREPLY']._serialized_start=352
  _globals['_ADDSEQUENCEREPLY']._serialized_end=387
  _globals['_GETSEQUENCELISTREQUEST']._serialized_start=389
  _globals['_GETSEQUENCELISTREQUEST']._serialized_end=443
  _globals['_GETSEQUENCELISTREPLY']._serialized_start=445
  _globals['_GETSEQUENCELISTREPLY']._serialized_end=497
# @@protoc_insertion_point(module_scope)
